In [1]:
print("Hello")

Hello


In [2]:
!pip install numpy
import numpy as np

In [5]:
print(np.__version__)

1.21.0


In [11]:
x=np.array(42)
print(x.ndim)
x=np.array([1,2,4,5,10])
print(x.ndim)
x=np.array([[1,2,4],[5,10,7]])
print(x.ndim)
x=np.array([[[1,2,4],[5,10,7]],
            [[10,20,40],[50,100,70]]
           ])
print(x.ndim)


0
1
2
3


In [14]:
x=np.array([1,2,3],ndmin=5)
print(x.ndim)
print(x)

5
[[[[[1 2 3]]]]]


In [29]:
x=np.array([[[1,2,4],[5,10,7]],
            [[10,20,40],[50,100,70]]
           ])
x=np.array([[1,2,4],
            [5,10,7],
            [11,22,33],
            [110,220,330],
           ])
print(x[-2:,-1])
# x=np.array([1,2,4,5,10])
# print(x[::-1])

[ 33 330]


In [47]:
arr = np.array([1, 2, 3, 4],dtype='u8')
arr[0]=2**64-1
print(arr)
print(arr.dtype)
arr[0]+=1
arr

[18446744073709551615                    2                    3
                    4]
uint64


array([9223372036854775808,                   2,                   3,
                         4], dtype=uint64)

In [43]:
print(2**63)

9223372036854775808


In [48]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [52]:
arr = np.array([1, 2, 3],dtype='U')
print(arr)
print(arr.dtype)

['1' '2' '3']
<U1


In [54]:
arr = np.array([1.1, 2.1, 3.9])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [59]:
arr = np.array([1.1, 0, 2])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
print(id(x),id(arr))

[42  2  3  4  5]
[1 2 3 4 5]
121748752 121748560


In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x)
print(id(x),id(arr))

[42  2  3  4  5]
[42  2  3  4  5]
121748128 121748128


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
print(id(x),id(arr))

[42  2  3  4  5]
[42  2  3  4  5]
121041744 121748848


In [70]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
z=arr

print(x.base)
print(y.base)
print(z.base)


None
[1 2 3 4 5]
None


In [78]:
import numpy as np

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8],
                [50, 60, 70, 80]])

print(arr.shape)
arr=arr.reshape(2,-1,2)
print(arr)


(3, 4)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [50 60]
  [70 80]]]


In [79]:
x=np.array(range(1,1001))
x=x.reshape(2,2,-1)
print(x)

[[[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
     15   16   17   18   19   20   21   22   23   24   25   26   27   28
     29   30   31   32   33   34   35   36   37   38   39   40   41   42
     43   44   45   46   47   48   49   50   51   52   53   54   55   56
     57   58   59   60   61   62   63   64   65   66   67   68   69   70
     71   72   73   74   75   76   77   78   79   80   81   82   83   84
     85   86   87   88   89   90   91   92   93   94   95   96   97   98
     99  100  101  102  103  104  105  106  107  108  109  110  111  112
    113  114  115  116  117  118  119  120  121  122  123  124  125  126
    127  128  129  130  131  132  133  134  135  136  137  138  139  140
    141  142  143  144  145  146  147  148  149  150  151  152  153  154
    155  156  157  158  159  160  161  162  163  164  165  166  167  168
    169  170  171  172  173  174  175  176  177  178  179  180  181  182
    183  184  185  186  187  188  189  190  191  19

In [83]:
import numpy as np

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8],
                [50, 60, 70, 80]])

for x in arr:
    print(x)
        
for x in arr:
    for y in x:
        print(y)

[1 2 3 4]
[5 6 7 8]
[50 60 70 80]
1
2
3
4
5
6
7
8
50
60
70
80


In [85]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [89]:
import numpy as np

arr = np.array([1000, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1000'
b'2'
b'3'


In [94]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [50, 60, 70, 80]])

for x in np.nditer(arr[::2, ::2]):
  print(x)

1
3
50
70


In [96]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [50, 60, 70, 80]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 50
(2, 1) 60
(2, 2) 70
(2, 3) 80


In [118]:
import numpy as np

arr1 = np.array([[[1, 2, 3]]])

arr2 = np.array([[[4, 5, 6]]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[[1 2 3]]

 [[4 5 6]]]


In [113]:
arr[1,0]

4

In [124]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [123]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# for x in arr:
#     print(x)
#     print("sssssssssss")

for x in arr:    
    for y in x:
        print(y)
        print("sssssss")
#         for z in y:
#             print(z)

[1 2 3]
sssssss
[4 5 6]
sssssss
[7 8 9]
sssssss
[10 11 12]
sssssss


In [126]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [127]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [135]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])

newarr = np.array_split(arr, 2)

print(type(newarr[1]))

<class 'numpy.ndarray'>


In [139]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [144]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [149]:
import numpy as np

arr = np.array([
                [1, 2, 3, 4, 5, 4, 4],
                [1, 2, 3, 4, 50, 4, 40]
               ])

x = np.where(arr == 4)

print(x)

(array([0, 0, 0, 1, 1], dtype=int32), array([3, 5, 6, 3, 5], dtype=int32))


In [150]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int32),)


In [154]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(3<arr)

print(x)

(array([3, 4, 5, 6, 7], dtype=int32),)


In [165]:
import numpy as np

arr = np.array([6, 7, 8, 90])

x = np.searchsorted(arr, 6.5, side='left')

print(x)

1


In [166]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [167]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [168]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [170]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
